project:
  type: website
  output-dir: docs

website:
  # title: "Team-On-Site-2023"
  navbar:
    logo: https://warwickinvestmentgroup.com/wp-content/uploads/2020/05/warwick-investment-group.png
    left:
      - href: index.qmd
        text: Home
      - agenda.qmd
    background: dark
    padding: 1px
    search: true

  sidebar:
      style: "docked"
      search: true
      contents:
        - section: "Overview"
          contents:
            - index.qmd
        - section: "Plan"
          contents:
            - agenda.qmd
format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    smooth-scroll: true
    # backgroundcolor: "crimson"




